language: "perl"
perl:
 - "5.18"
 - "5.16"
 - "5.14"
install: 
 - "cd ./IO-Routine; perl Makefile.PL && make && make test"
script:
 - "cd ../NGS-Utils; perl ncRNAScan -setup"
notifications:
  email: false